# Generated by Django 5.1.6 on 2025-03-02 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_genres', models.TextField(blank=True, help_text='Comma-separated genres', null=True)),
                ('favorite_authors', models.TextField(blank=True, help_text='Comma-separated authors', null=True)),
                ('books_read', models.JSONField(default=list, help_text='List of books read')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
