# Generated by Django 5.1.6 on 2025-03-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_books_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reading_goal_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reading_goal_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reading_goal_year',
            field=models.IntegerField(default=2025),
        ),
    ]
