# Generated by Django 5.1.6 on 2025-03-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_reading_goal_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookshelf',
            name='user_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='bookshelf',
            name='status',
            field=models.CharField(choices=[('to_read', 'To Read'), ('reading', 'Currently Reading'), ('read', 'Read')], default='to_read', max_length=10),
        ),
    ]
