# Generated by Django 5.1.6 on 2025-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bookshelf_page_count_bookshelf_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='page_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
