# Generated by Django 5.1.6 on 2025-03-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_bookshelf_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
