# Generated by Django 5.1.6 on 2025-03-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mediarecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookshelf',
            name='categories',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
