# Generated by Django 5.1.6 on 2025-03-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_bookshelf_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookshelf',
            name='categories',
            field=models.JSONField(default=list, help_text='List of categories'),
        ),
    ]
