# Generated by Django 5.1.6 on 2025-03-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_bookshelf_categories'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MediaRecommendation',
        ),
    ]
