# Generated by Django 5.0.3 on 2025-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookclub',
            name='current_book_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookclub',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
