# Generated by Django 5.1.6 on 2025-03-22 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100)),
                ('book_title', models.CharField(max_length=255)),
                ('movie_id', models.CharField(max_length=100)),
                ('movie_title', models.CharField(max_length=255)),
                ('movie_poster', models.URLField(blank=True, max_length=1000, null=True)),
                ('movie_overview', models.TextField(blank=True, null=True)),
                ('movie_release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'book_id', 'movie_id')},
            },
        ),
    ]
